default: &default
  adapter: postgresql
  encoding: utf8
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: eat_back_development
  username: eatback
  password:

test:
  <<: *default
  database: eat_back_test
  username: eatback
  password:

production:
  <<: *default
  database: eat_back_production
  username: myapp
  password: <%= ENV['EAT_BACK_PROD_PG_PASS'] %>
