default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: eat_back_development
  username: eatback
  password:
  host: localhost

test:
  <<: *default
  database: eat_back_test
  username: eatback
  password:
  host: localhost

production:
  <<: *default
  database: eat_back_production
  username: myapp
  password: <%= ENV['EAT_BACK_PROD_PG_PASS'] %>
